version: "3.3"

services:
  server:
    image: node:lts-alpine
    env_file: docker/server/env
    volumes:
      - ./:/app/
    working_dir: /app
    ports:
      - 3000:3000
    command: ash -c "npm install && npm run dev"

